# Uncomment this line to define a global platform for your project (home_widget requires 14.0+)
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # 동적 프레임워크만 쓰면 GeneratedPluginRegistrant 의 @import app_links 등에서 모듈을 못 찾는 경우가 있음
  use_frameworks! :linkage => :static
  # Swift 플러그인(app_links 등) 모듈 맵을 ObjC Runner 가 찾도록
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

def patch_app_links_generated_plugin_registrant!
  path = File.join(__dir__, 'Runner', 'GeneratedPluginRegistrant.m')
  return unless File.file?(path)

  contents = File.read(path)
  return if contents.include?('app_links-Swift.h')

  old_block = <<~'PATCH'
#if __has_include(<app_links/AppLinksIosPlugin.h>)
#import <app_links/AppLinksIosPlugin.h>
#else
@import app_links;
#endif
PATCH
  new_block = <<~'PATCH'
// Swift 전용 app_links: 생성 헤더 우선 (flutter pub get 이 덮어쓰므로 pod install 시 재적용)
#if __has_include(<app_links/app_links-Swift.h>)
#import <app_links/app_links-Swift.h>
#elif __has_include(<app_links/AppLinksIosPlugin.h>)
#import <app_links/AppLinksIosPlugin.h>
#else
@import app_links;
#endif
PATCH
  unless contents.include?(old_block.strip)
    STDERR.puts "[Podfile] GeneratedPluginRegistrant.m: app_links 블록이 예상과 다릅니다. 수동으로 Swift 헤더 분기를 확인하세요."
    return
  end

  File.write(path, contents.sub(old_block.strip, new_block.strip))
  STDERR.puts '[Podfile] GeneratedPluginRegistrant.m: app_links → app_links-Swift.h 분기 적용됨'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  patch_app_links_generated_plugin_registrant!
end
